from __future__ import annotations


MVP_UI = r'''<!doctype html>
<html lang="vi"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>Gladiators · E-commerce Analyst</title>
<style>
:root{color-scheme:dark;--bg:#08111f;--panel:#101c2e;--line:#26364d;--text:#edf3fb;--muted:#9dafc7;--accent:#72e6c1;--warn:#ffc86b}*{box-sizing:border-box}body{margin:0;min-height:100vh;font:15px/1.55 Inter,ui-sans-serif,system-ui,sans-serif;color:var(--text);background:radial-gradient(circle at 15% 0,#17334b 0,transparent 35%),var(--bg)}main{width:min(920px,calc(100% - 32px));margin:48px auto}header{margin-bottom:24px}h1{margin:0 0 6px;font-size:clamp(28px,5vw,46px);letter-spacing:-.04em}header p,.muted{color:var(--muted)}.card{padding:22px;border:1px solid var(--line);border-radius:18px;background:#101c2eee;box-shadow:0 20px 60px #0005}form{display:flex;gap:10px}textarea{width:100%;min-height:92px;resize:vertical;padding:14px 16px;border:1px solid var(--line);border-radius:12px;color:var(--text);background:#091525;font:inherit;outline:none}textarea:focus{border-color:var(--accent)}button{align-self:stretch;min-width:110px;border:0;border-radius:12px;padding:0 18px;background:var(--accent);color:#062018;font-weight:750;cursor:pointer}button:disabled{opacity:.55;cursor:wait}.examples{display:flex;flex-wrap:wrap;gap:8px;margin-top:14px}.chip{min-width:0;padding:7px 11px;border:1px solid var(--line);border-radius:999px;background:#142238;color:var(--muted);font-weight:500}.chip:hover{color:var(--text);border-color:#49617f}#result{display:none;margin-top:18px}.status{display:inline-block;padding:4px 9px;border-radius:999px;background:#183b35;color:var(--accent);font-size:12px;font-weight:800;text-transform:uppercase}.status.warn{background:#45351c;color:var(--warn)}#answer{white-space:pre-wrap;font-size:16px}.grid{display:grid;grid-template-columns:repeat(auto-fit,minmax(220px,1fr));gap:10px}.evidence{padding:12px;border:1px solid var(--line);border-radius:11px;background:#0b1728}.evidence strong{color:var(--accent)}details{margin-top:14px;color:var(--muted)}pre{overflow:auto;white-space:pre-wrap;font-size:12px}@media(max-width:620px){main{margin:24px auto}form{display:block}button{width:100%;height:46px;margin-top:10px}}
</style></head><body><main>
<header><div class="muted">GLADIATORS V1 · INTERNAL MVP</div><h1>Hỏi dữ liệu e-commerce.</h1><p>Phân tích sales, sản phẩm tương tự và voucher với evidence có kiểm chứng.</p></header>
<section class="card"><form id="ask"><textarea id="question" maxlength="4000" autofocus placeholder="Ví dụ: Voucher ở VN có hiệu quả không?"></textarea><button id="submit">Phân tích</button></form><div class="examples">
<button class="chip" type="button">Voucher ở VN có hiệu quả không?</button><button class="chip" type="button">Phân tích giảm sales của &quot;SCORA D-Panthenol Gentle Low pH Cleanser 100ml&quot;</button><button class="chip" type="button">Tìm sản phẩm tương tự &quot;Scora Hydra Calm Cica Soothing Moisturizer 40ml&quot;</button><button class="chip" type="button">Dự báo doanh số tháng sau</button></div></section>
<section id="result" class="card"><span id="status" class="status"></span><p id="answer"></p><h3>Evidence</h3><div id="evidence" class="grid"></div><details><summary>Chi tiết kỹ thuật</summary><pre id="raw"></pre></details></section>
</main><script>
const form=document.querySelector('#ask'),input=document.querySelector('#question'),submit=document.querySelector('#submit');document.querySelectorAll('.chip').forEach(x=>x.onclick=()=>{input.value=x.textContent;input.focus()});form.onsubmit=async e=>{e.preventDefault();const text=input.value.trim();if(!text)return;submit.disabled=true;submit.textContent='Đang chạy…';try{const res=await fetch('/ask',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({text})});const data=await res.json();if(!res.ok)throw new Error(data.detail?.code||'Request failed');const action=data.gate?.action||'unknown',badge=document.querySelector('#status');badge.textContent=action;badge.className='status'+(action==='allow'?'':' warn');document.querySelector('#answer').textContent=data.answer;const box=document.querySelector('#evidence');box.innerHTML='';(data.evidence||[]).forEach(ev=>{const el=document.createElement('div');el.className='evidence';el.innerHTML=`<strong>${esc(ev.metric)}</strong><br>${esc(String(ev.value))} ${esc(ev.unit||'')}<br><small>${esc(ev.evidence_id)}</small>`;box.appendChild(el)});if(!data.evidence?.length)box.innerHTML='<span class="muted">Không có evidence cho phản hồi này.</span>';document.querySelector('#raw').textContent=JSON.stringify(data,null,2);document.querySelector('#result').style.display='block'}catch(err){document.querySelector('#result').style.display='block';document.querySelector('#answer').textContent='Lỗi: '+err.message}finally{submit.disabled=false;submit.textContent='Phân tích'}};function esc(s){return s.replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]))}
</script></body></html>'''
